spring.application.name=neobank

# 1. URL ????? ???? ?????? (localhost ? ???? ???? ?? ????? ?????, 5432 ? ??????????? ????)
# ??????????? ?????? "neobank" ? ????? ?? ???????? ??? ????, ??????? ?? ?????? ? PostgreSQL!
spring.datasource.url=jdbc:postgresql://localhost:5432/neobank

# 2. ????? ? ?????? ?? ?????? PostgreSQL (?????? ?? ????????? ?????: postgres)
spring.datasource.username=postgres
spring.datasource.password=postgres

# 3. ??????? ??? ?????? ? ?????
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. ????????? Hibernate (?????????????? ???????? ??????)
# ??? ?????? ??????? ???????? "update".
# ??? ??????, ??? Spring ??? ????????? ?? ???? Java-?????? ? @Entity ? ???????/??????? ??? ??? ??????? ? ????.
spring.jpa.hibernate.ddl-auto=update

# (???????????) ?????????? ? ??????? SQL-???????, ??????? Spring ?????????? ? ????. ????? ?????? ??? ???????!
spring.jpa.show-sql=true